//arduino_secrets.h header file

#define SECRET_SSID "YOUR_WIRELESS_SSID"
#define SECRET_PASS "YOUR_WIRELESS_PASSWORD"

// Influxdb stuff
#define INFLUXDB_URL "http:/YOUR_INFLUXDB_HOSTNAME:8086"
#define INFLUXDB_TOKEN "YOUR_INFLUXDB2_TOKEN"
#define INFLUXDB_ORG "YOUR_INFLUXv2_TOKEN"
#define INFLUXDB_BUCKET "YOUR_INFLUXv2_ORG"
#define INFLUXDB_MEASUREMENT "MEASUREMENT_TO_PUT_THIS_IN"
#define OZONE_FIELD "Ozone_PBB"